### ISSUE TITLE
main window automatically shrink small

### ISSUE THREAD

**Issue by haobug** [iptux-src/iptux#16]
main window will shrink small automatically, manual adjustment make no change.

here is the screenshot
http://picpaste.com/QQ__20130619155519-6vxSHsyW.png

distro: ubuntu 
desktop environment: unity

**Comment by ravipatel071292** [comment]
Following is the steps to reproduce the bug : 
1.  Open Iptux
2.  Double click on title bar of iptux OR press maximize button on title bar to maximize it.
3.  Now Double click on title bar of iptux OR press re-size button on title bar to re-size to original size.
4.  Main window of iptux is automatically shrinking to smallest size.

Above steps are used when iptux installed on first time. Once this issue is produced it is permanent until you format your machine.
